language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - ruby-head

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email: false